events {
    worker_connections 1024;
}

http {
    server {
        listen 443 ssl;
        server_name psirault.42.fr;

        ssl_certificate /etc/nginx/ssl/psirault.crt;
        ssl_certificate_key /etc/nginx/ssl/psirault.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        location / {
            root /var/www/html;
            index index.php;
        }
    }
}
